# Generated by Django 4.2.16 on 2024-11-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_person_person_name_person_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_name',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
