# Generated by Django 4.2.16 on 2024-11-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_person_person_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marrid',
            name='image',
        ),
        migrations.AddField(
            model_name='marrid',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
