# Generated by Django 4.2.16 on 2024-11-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_taskdead_taskdivorce_taskmarrid_taskperson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dead',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='divorce',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='marrid',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='taskdead',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='taskdivorce',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='taskmarrid',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='taskperson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='taskwidower',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='widower',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/%y/%m/%d'),
        ),
    ]
