# Generated by Django 4.2.16 on 2024-11-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_dead_image_alter_divorce_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmarrid',
            name='national_wife',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='taskperson',
            name='national_num',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='taskperson',
            name='person_name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
