# Generated by Django 4.2.16 on 2024-11-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_taskmarrid_national_wife_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dad_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='mom_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='taskperson',
            name='dad_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='taskperson',
            name='mom_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='taskperson',
            name='national_dad',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='taskperson',
            name='national_mom',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
