# Generated by Django 4.2.16 on 2024-11-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_person_dad_name_person_mom_name_taskperson_dad_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskperson',
            name='date_of_event',
            field=models.DateField(null=True),
        ),
    ]
