# Generated by Django 4.2.16 on 2024-11-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_taskperson_date_of_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskperson',
            name='code',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
