# Generated by Django 4.2.16 on 2024-11-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_taskperson_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskDead',
        ),
        migrations.DeleteModel(
            name='TaskDivorce',
        ),
        migrations.DeleteModel(
            name='TaskMarrid',
        ),
        migrations.DeleteModel(
            name='TaskWidower',
        ),
        migrations.AddField(
            model_name='taskperson',
            name='place_of_event',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='widower',
            name='date_of_divorce',
            field=models.DateField(null=True),
        ),
    ]
