# Generated by Django 4.2.16 on 2024-11-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_taskdead_delete_taskdivorce_delete_taskmarrid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dead',
            old_name='date_of_death',
            new_name='date_of_event',
        ),
        migrations.RenameField(
            model_name='divorce',
            old_name='date_of_divorce',
            new_name='date_of_event',
        ),
        migrations.RenameField(
            model_name='marrid',
            old_name='date_of_marrid',
            new_name='date_of_event',
        ),
        migrations.RemoveField(
            model_name='dead',
            name='place_of_death',
        ),
        migrations.AddField(
            model_name='dead',
            name='place_of_event',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='divorce',
            name='place_of_event',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='marrid',
            name='place_of_event',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
