# Generated by Django 4.2.16 on 2024-11-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_date_of_death_dead_date_of_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/%y/%m/%d'),
        ),
    ]
